### PR TITLE
[+] Allow banning ip

### PR DESCRIPTION
**Pull request by hykilpikonna**
Completes #1

### CODE REVIEW

**Comment by sauricat** [comment]
Thank you for your hard work! I approve this change but request @Mak1owo to review it from the technical perspective.

**Review by septs — COMMENTED** [review]
suggest, support CIDR format

private network group, e.g: `127.0.0.0/8`, `172.16.0.0/12`, `192.168.0.0/16`, `10.0.0.0/8`, etc

see https://en.wikipedia.org/wiki/Classless_Inter-Domain_Routing
see https://en.wikipedia.org/wiki/Private_network
see https://en.wikipedia.org/wiki/Wikipedia:Database_reports/Range_blocks

**Comment by hykilpikonna** [comment]
> suggest, support CIDR format

It's not necessary, we're never going to ban an entire ip block at once...

**Comment by hykilpikonna** [comment]
Also just added AI classification (closed sourced for now)

**Pull request merged**
